customer/urls.py
from django.urls import path
from customer import views

app_name = 'customer'

urlpatterns = [
    path('getreservation/', views.getreservation, name='getreservation'),
    path('getfeedback/', views.getfeedback, name='getfeedback'),
    path('productshow', views.productshow, name='productshow'),
    # path('showcart/', views.showcart, name='showcart'),
    path('showfav/', views.showfav, name='showfav'),
    path('addtofav/<int:id>/', views.addtofav, name='addtofav'),



]

login/urls.py
from django.urls import path
from login import views

app_name = 'login'

urlpatterns = [
    path('signupcompany/', views.signupcompany, name='signupcompany'),
    path('', views.index, name='index'),
    path('logincompany/', views.logincompany, name='logincompany'),
    path('signupcustomer/', views.signupcustomer, name='signupcustomer'),
    path('logincustomer/', views.logincustomer, name='logincustomer'),
    path('afterlogincompany/', views.afterlogincompany, name='afterlogincompany'),
    path('afterlogincustomer/', views.afterlogincustomer,
         name='afterlogincustomer'),
    path('logout/', views.logout_user, name='logout'),
    path('', views.index, name='index'),




]

tastyfood/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('company.urls')),
    path('', include('customer.urls')),
    path('', include('login.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/models.py
from django.db import models
from django.conf import settings
from company.models import food


class reservation(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True,
                             on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    no_of_people = models.PositiveIntegerField()
    date = models.DateField(auto_now=False, auto_now_add=False)
    mobile = models.PositiveIntegerField()
    email = models.EmailField()
    location = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    food = models.ForeignKey(food, on_delete=models.CASCADE)


class favourite(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    food = models.ForeignKey(food, on_delete=models.CASCADE)


class feedback(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)
    reservation = models.ForeignKey(
        reservation, null=True, on_delete=models.CASCADE, default=1)
    title = models.CharField(max_length=122)
    feedback = models.CharField(max_length=122)

    def __str__(self):
        return self.title

customer/forms.py
from django.forms import ModelForm
from django import forms
from .models import *


class CreateReservation(ModelForm):

    class Meta:
        model = reservation
        fields = '__all__'
        exclude = ['user']

customer/views.py
from django.shortcuts import render, redirect
from .forms import *

from django.contrib.auth import get_user_model
User = get_user_model()


def getreservation(request):

    form = CreateReservation()
    if request.method == 'POST':
        form = CreateReservation(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()

    context = {'form': form}

    return render(request, 'customer/getreservation.html', context)


def productshow(request):
    blogs = food.objects.all()
    context = {'blogs': blogs}

    return render(request, 'customer/productshow.html', locals())


def getfeedback(request):

    la = reservation.objects.get(user=request.user)
    res = feedback.objects.filter(reservation=la)

    return render(request, 'customer/getfeedback.html', locals())


def addtofav(request, id):
    ti = food.objects.get(id=id)
    post = favourite(food=ti, user=request.user)
    post.save()

    return render(request, 'customer/addtofav.html', locals())


def showfav(request):
    blogs = favourite.objects.filter(user= request.user)

    context = {'blogs': blogs}
    return render(request, 'customer/showfav.html', context)

# def showcart(request):
#     blogs = cart.objects.all()

#     context = {'blogs': blogs}
#     return render(request, 'customer/showblog.html', context)

# def liked(request, pk):
#     blog = Blog.objects.get(pk=pk)
#     user = request.user
#     already_liked = Likes.objects.filter(blog=blog, user=user)
#     if not already_liked:
#         liked_post = Likes(blog=blog, user=user)
#         liked_post.save()
#     return HttpResponseRedirect(reverse('App_Blog:blog_details', kwargs={'slug':blog.slug}))


# def showfav(request):
#     blogs = favourite.objects.all()

#     context = {'blogs': blogs}
#     return render(request, 'customer/showblog.html', context)


# def getreservation(request):
#     return render(request, 'customer/getreservation.html', locals())

templates/customer/addtofav.html
{% extends 'customer/base2.html' %} {% load crispy_forms_tags %} {% block body%}
<h1 style="color: green">added to favourite</h1>
{% endblock %}

templates/customer/afterlogincustomer.html
{% extends "customer/base2.html" %} {% block body %}

<div class="container-fluid">
  <div class="row">
    <nav
      id="sidebar"
      class="col-md-3 col-lg-2 d-md-block sidebar collapse"
      style="background-color: #ac4343; height: 600px"
    >
      <div class="position-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="">
              <i class="fa-solid fa-prescription-bottle-medical"></i>
              <span class="ml-2" style="color: black">add food</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">
              <i class="fa-solid fa-prescription-bottle-medical"></i>
              <span class="ml-2" style="color: black">add blog</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">
              <i class="fa-solid fa-user-doctor"></i>
              <span class="ml-2" style="color: black">add location</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">
              <i class="fa-solid fa-user-doctor"></i>
              <span class="ml-2" style="color: black">get reservations</span>
            </a>
          </li>
        </ul>
      </div>
    </nav>
    <main class="col-md-9 ml-sm-auto col-lg-10 px-md-4 py-4">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
          <li class="breadcrumb-item active" aria-current="page">Overview</li>
        </ol>
      </nav>
      <h1 class="h2">Dashboard</h1>
      <p style="background-color: #add8e6">hello! {{request.user}}</p>
      <div class="row my-4">
        <div class="col-12 col-md-6 col-lg-3 mb-4 mb-lg-0">
          <div class="card">
            <h5 class="card-header">Menu set</h5>
            <div class="card-body">
              <h5 class="card-title">50</h5>
              <p class="card-text">Feb 1 - Apr 1</p>
              <p class="card-text text-success">
                18.2% increase since last month
              </p>
            </div>
          </div>
        </div>
        <div class="col-12 col-md-6 mb-4 mb-lg-0 col-lg-3">
          <div class="card">
            <h5 class="card-header">reservations</h5>
            <div class="card-body">
              <h5 class="card-title">100</h5>
              <p class="card-text">Feb 1 - Apr 1</p>
              <p class="card-text text-success">
                4.6% increase since last month
              </p>
            </div>
          </div>
        </div>
        <div class="col-12 col-md-6 mb-4 mb-lg-0 col-lg-3">
          <div class="card">
            <h5 class="card-header">workers</h5>
            <div class="card-body">
              <h5 class="card-title">43</h5>
              <p class="card-text">Feb 1 - Apr 1</p>
              <p class="card-text text-danger">
                2.6% decrease since last month
              </p>
            </div>
          </div>
        </div>
        <div class="col-12 col-md-6 mb-4 mb-lg-0 col-lg-3">
          <div class="card">
            <h5 class="card-header">details</h5>
            <div class="card-body">
              <h5 class="card-title">1000</h5>
              <p class="card-text">Feb 1 - Apr 1</p>
              <p class="card-text text-success">
                2.5% increase since last month
              </p>
            </div>
          </div>
        </div>
      </div>
    </main>
  </div>
</div>

{% endblock %}

templates/customer/base2.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" />
    <!-- Latest compiled and minified CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
      integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link rel="stylesheet" href="static/css/style.css" />
    <title>{% block title_block %} Blogs {% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-white shadow py-3 sticky-top">
      <div class="container">
        <a class="navbar-brand" href="/">
          <b>
            <h3>Tasty <span style="color: #da2626">Food</span></h3></b
          >
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mx-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login:afterlogincustomer' %}"
                >About</a
              >
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'customer:productshow' %}"
                >productshow</a
              >
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'customer:getreservation' %}"
                >get Reservation</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'customer:getfeedback' %}"
                >get feedback</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'customer:showfav' %}"
                >show fav</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login:logout' %}">logout</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% block body %} {% endblock %}

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/customer/getfeedback.html
{% extends 'customer/base2.html' %} {% block body %}

<div class="container my-3 b1">
  <h3>feedbacks:</h3>
  {% for r in res %}

  <div class="container">
    <h1 class="alert-danger text-center p-3">feedback Detail</h1>
    <div class="row">
      <div class="col-sm-10 shadow p-5 offset-sm-1">
        <h3 class="text-center"><u>details</u></h3>

        <p>Title: {{r.title}}</p>
        <p>Feedback: {{r.feedback}}</p>
      </div>
    </div>
  </div>
</div>
{% endfor %} {% endblock %}

templates/customer/getreservation.html
{% extends 'customer/base2.html' %} {% load crispy_forms_tags %} {% block body%}
<div class="container">
  <h2>make reservations:</h2>
  <form method="POST" enctype="multipart/form-data">
    {{form|crispy}} {% csrf_token %}
    <br />
    <button type="submit" class="btn btn-primary btn-sm">Login</button>
  </form>
</div>
{% endblock %}

templates/customer/productshow.html
{% extends 'customer/base2.html' %} {% load crispy_forms_tags %} {% block body %}
<section id="blog">
  <div class="container">
    <div class="row">
      <div class="col-12 intro-text">
        <h1>dishes</h1>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae
          sint temporibus natus optio eveniet nobis accusantium?
        </p>
      </div>
    </div>

    <div class="row gy-4">
      {% for blog in blogs %}
      <div class="col-sm-6 p-2 ">
        <img src="{{blog.image.url}}" width="300px" height="200px" alt="" />

        <p>{{blog.publish_date}}</p>
        <p>{{blog.type}}</p>
        <h4><a href="#">{{blog.name}}</a></h4>
        <p>{{blog.describtion}}</p>
        <div  >
          <a href="{% url 'customer:addtofav' id=blog.id %}"><i class="fa-solid fa-heart" style="color: brown; margin-left: 30px "></i></a>

          <a href="#"
            ><i
              class="fa-regular fa-eye fa-lg"
              style="color: brown; margin-left: 30px"
            ></i
          ></a>
          <a href="#"
            ><i
              class="fa-solid fa-cart-shopping fa-lg"
              style="color: brown; margin-left: 30px"
            ></i
          ></a>
        </div>
        <br>
        <a style="border-radius: 5px; background-color: rgb(179, 61, 61); color: azure; padding: 20px;" href="#">Read More</a>
      </div>
    
    {%endfor%}
  </div>
</section>

{% endblock %}

templates/customer/showfav.html
{% extends 'customer/base2.html' %} {% load crispy_forms_tags %} {% block body %}

<section id="blog">
  <div class="container">
    <div class="row">
      <div class="col-12 intro-text">
        <h1>favourite dishes</h1>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae
          sint temporibus natus optio eveniet nobis accusantium?
        </p>
      </div>
    </div>

    <div class="row gy-4">
      {% for blog in blogs %}
      <div class="col-sm-6 p-2 ">
        <img src="{{blog.food.image.url}}" width="300px" height="200px" alt="" />

        <p>{{blog.food.publish_date}}</p>
        <p>{{blog.food.type}}</p>
        <h4><a href="#">{{blog.food.name}}</a></h4>
        <p>{{blog.food.describtion}}</p>
       
        <br>
        <a style="border-radius: 5px; background-color: rgb(179, 61, 61); color: azure; padding: 20px;" href="#">Read More</a>
      </div>
    
    {%endfor%}
  </div>
</section>

{% endblock %}