company/urls.py
from django.urls import path
from company import views

app_name = 'company'

urlpatterns = [
    path('addfood/', views.addfood, name='addfood'),
    path('addfeedback/<str:id>/', views.addfeedback, name='addfeedback'),
    path('addblog/', views.addblog, name='addblog'),
    path('showblog/', views.showblog, name='showblog'),
    path('showfood/', views.showfood, name='showfood'),
    path('getresponse/', views.getresponse, name='getresponse'),
    # path('afterlogincustomer/', views.afterlogincustomer,name='afterlogincustomer'),
    # path('logout/', views.logout_user, name='logout'),





]

login/urls.py
from django.urls import path
from login import views

app_name = 'login'

urlpatterns = [
    path('signupcompany/', views.signupcompany, name='signupcompany'),
    path('', views.index, name='index'),
    path('logincompany/', views.logincompany, name='logincompany'),
    path('signupcustomer/', views.signupcustomer, name='signupcustomer'),
    path('logincustomer/', views.logincustomer, name='logincustomer'),
    path('afterlogincompany/', views.afterlogincompany, name='afterlogincompany'),
    path('afterlogincustomer/', views.afterlogincustomer,
         name='afterlogincustomer'),
    path('logout/', views.logout_user, name='logout'),
    path('', views.index, name='index'),




]

tastyfood/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('company.urls')),
    path('', include('customer.urls')),
    path('', include('login.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

company/models.py
from django.db import models

# Create your models here.
# from customer.models import reservation
from django.conf import settings


class food(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=122)
    type = models.CharField(max_length=122)
    describtion = models.TextField()
    price = models.CharField(max_length=122)
    image = models.ImageField(upload_to='profileimg', blank=True)

    def __str__(self):
        return self.name


class blog(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             null=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=122)
    describtion = models.TextField()
    image = models.ImageField(upload_to='profileimg', blank=True)
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

company/forms.py
from django.forms import ModelForm
from django import forms
from .models import *
from customer.models import *


class CreateFoodForm(ModelForm):
    class Meta:
        model = food
        fields = '__all__'
        exclude = ['user']


class CreateBlog(ModelForm):
    class Meta:
        model = blog
        fields = '__all__'
        exclude = ['user']


class CreateFeedback(ModelForm):
    class Meta:
        model = feedback
        fields = '__all__'
        exclude = ['user', 'reservation']

company/views.py
from django.shortcuts import render, redirect
from .forms import *
from customer.models import reservation
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
User = get_user_model()


@login_required
def addfood(request):
    form = CreateFoodForm()
    if request.method == 'POST':
        form = CreateFoodForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()

    context = {'form': form}

    return render(request, 'company/addfood.html', context)


@login_required
def addblog(request):
    form = CreateBlog()
    if request.method == 'POST':
        form = CreateBlog(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('/showblog')

    return render(request, 'company/addblog.html', locals())


@login_required
def showfood(request):
    blogs = food.objects.all()

    context = {'blogs': blogs}

    return render(request, 'company/showfood.html', locals())


@login_required
def showblog(request):
    blogs = blog.objects.all()

    context = {'blogs': blogs}
    return render(request, 'company/showblog.html', context)


@login_required
def getresponse(request):
    blogs = reservation.objects.all()

    context = {'blogs': blogs}
    return render(request, 'company/getresponse.html', locals())


@login_required
def addfeedback(request, id):
    res = reservation.objects.get(id=id)
    form = CreateFeedback()
    if request.method == 'POST':
        form = CreateFeedback(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.reservation = res
            post.save()

    context = {'form': form}
    # res = reservation.objects.get(id=id)
    # form = CreateFeedback()
    # if request.method == 'POST':
    #     print(res)
    #     form = CreateFeedback(request.POST)
    #     if form.is_valid():
    #         form.user = request.user
    #         form.reservation = res
    #         form.save()

    return render(request, 'company/addfeedback.html', locals())

templates/company/addblog.html
{% extends 'company/base1.html' %} {% load crispy_forms_tags %} {% block body%}
<div class="container">
  <h2>add blog:</h2>
  <form method="POST" enctype="multipart/form-data">
    {{form|crispy}} {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-sm">Login</button>
  </form>
</div>
{% endblock %}

templates/company/addfeedback.html
{% extends 'company/base1.html' %} {% load crispy_forms_tags %} {% block body %}

<div class="container">
  <h3>add feedback:</h3>
  <form action="" method="POST">
    {{form|crispy}} {% csrf_token %}

    <input type="submit" name="Submit" />
  </form>
</div>

{% endblock %}

templates/company/addfood.html
{% extends 'company/base1.html' %} {% load crispy_forms_tags %} {% block body %}

<div class="container">
  <h3>add dish:</h3>
  <form action="" method="POST" enctype="multipart/form-data">
    {{form|crispy}} {% csrf_token %}

    <input type="submit" name="Submit" />
  </form>
</div>

{% endblock %}

templates/company/afterlogincompany.html
{% extends "company/base1.html" %} {% block body %}

<div class="container-fluid">
  <div class="row">
    <nav
      id="sidebar"
      class="col-md-3 col-lg-2 d-md-block sidebar collapse"
      style="background-color: #ac4343; height: 600px"
    >
      <div class="position-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="">
              <i class="fa-solid fa-prescription-bottle-medical"></i>
              <span class="ml-2" style="color: black">add food</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">
              <i class="fa-solid fa-prescription-bottle-medical"></i>
              <span class="ml-2" style="color: black">add blog</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">
              <i class="fa-solid fa-user-doctor"></i>
              <span class="ml-2" style="color: black">add location</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">
              <i class="fa-solid fa-user-doctor"></i>
              <span class="ml-2" style="color: black">get reservations</span>
            </a>
          </li>
        </ul>
      </div>
    </nav>
    <main class="col-md-9 ml-sm-auto col-lg-10 px-md-4 py-4">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
          <li class="breadcrumb-item active" aria-current="page">Overview</li>
        </ol>
      </nav>
      <h1 class="h2">Dashboard</h1>
      <p style="background-color: #add8e6">hello!{{request.user}}</p>
      <div class="row my-4">
        <div class="col-12 col-md-6 col-lg-3 mb-4 mb-lg-0">
          <div class="card">
            <h5 class="card-header">Menu set</h5>
            <div class="card-body">
              <h5 class="card-title">50</h5>
              <p class="card-text">Feb 1 - Apr 1</p>
              <p class="card-text text-success">
                18.2% increase since last month
              </p>
            </div>
          </div>
        </div>
        <div class="col-12 col-md-6 mb-4 mb-lg-0 col-lg-3">
          <div class="card">
            <h5 class="card-header">reservations</h5>
            <div class="card-body">
              <h5 class="card-title">100</h5>
              <p class="card-text">Feb 1 - Apr 1</p>
              <p class="card-text text-success">
                4.6% increase since last month
              </p>
            </div>
          </div>
        </div>
        <div class="col-12 col-md-6 mb-4 mb-lg-0 col-lg-3">
          <div class="card">
            <h5 class="card-header">workers</h5>
            <div class="card-body">
              <h5 class="card-title">43</h5>
              <p class="card-text">Feb 1 - Apr 1</p>
              <p class="card-text text-danger">
                2.6% decrease since last month
              </p>
            </div>
          </div>
        </div>
        <div class="col-12 col-md-6 mb-4 mb-lg-0 col-lg-3">
          <div class="card">
            <h5 class="card-header">details</h5>
            <div class="card-body">
              <h5 class="card-title">1000</h5>
              <p class="card-text">Feb 1 - Apr 1</p>
              <p class="card-text text-success">
                2.5% increase since last month
              </p>
            </div>
          </div>
        </div>
      </div>
    </main>
  </div>
</div>

{% endblock %}

templates/company/base1.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" />
    <!-- Latest compiled and minified CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
      integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />

    <link rel="stylesheet" href="static/css/style.css" />
    <title>{% block title_block %} Blogs {% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-white shadow py-3 sticky-top">
      <div class="container">
        <a class="navbar-brand" href="/">
          <b>
            <h3>Tasty <span style="color: #da2626">Food</span></h3></b
          >
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mx-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login:afterlogincompany' %}"
                >About</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'company:addfood' %}"
                >add food</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'company:addblog' %}"
                >add blog</a
              >
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'company:getresponse' %}"
                >get Reservation</a
              >
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'company:showfood' %}"
                >show food</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'company:showblog' %}"
                >show blog</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login:logout' %}">logout</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% block body %} {% endblock %}

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/company/getresponse.html
{% extends 'company/base1.html' %} {% load crispy_forms_tags %} {% block body %}

<section id="blog">
  <div class="container">
    <div class="row">
      <div class="col-12 intro-text">
        <h1>get response</h1>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae
          sint temporibus natus optio eveniet nobis accusantium?
        </p>
      </div>
    </div>
  
    <div class="row gy-4">
      {% for blog in blogs %}
      
      <div class="col-sm-6 p-2">
        <div class="blog-post d-flex shadow-on-hover">
          <div class="blog-post-content p-4">
            <p>Name: {{blog.name}}</p>
            <p>City: {{blog.city}}</p>
            <p>No of people : {{blog.no_of_people}}</p>
            <p>Mobile : {{blog.mobile}}</p>
            <p>Email: {{blog.email}}</p>
            <p>location: {{blog.location}}</p>
         
            <a class="btn btn-success btn-sm " href="{% url 'company:addfeedback' id=blog.id %}">send feedback</a>

          </div>
        </div>
       
      </div>
      {%endfor%}
  </div>
</section>

{% endblock %}

templates/company/showblog.html
{% extends 'company/base1.html' %} {% load crispy_forms_tags %} {% block body %}

<section id="blog">
  <div class="container">
    <div class="row">
      <div class="col-12 intro-text">
        <h1>Blog Posts</h1>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae
          sint temporibus natus optio eveniet nobis accusantium?
        </p>
      </div>
    </div>
  
    <div class="row gy-4">
      {% for blog in blogs %}
      <div class="col-sm-6 p-2">
        <div class="blog-post d-flex shadow-on-hover">
            <img src="{{blog.image.url}}" width="300px" height="200px" alt="" />
          <div class="blog-post-content p-4">
            <p>{{blog.publish_date}}</p>
            <h4><a href="#">{{blog.title}}</a></h4>
            <p>
              {{blog.describtion}}
            </p>
            <a href="#">Read More</a>
          </div>
        </div>
       
      </div>
      {%endfor%}
  </div>
</section>

{% endblock %}

templates/company/showfood.html
{% extends 'company/base1.html' %} {% load crispy_forms_tags %} {% block body %}

<section id="blog">
  <div class="container">
    <div class="row">
      <div class="col-12 intro-text">
        <h1>dishes</h1>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae
          sint temporibus natus optio eveniet nobis accusantium?
        </p>
      </div>
    </div>

    <div class="row gy-4">
      {% for blog in blogs %}
      <div class="col-sm-6 p-2">
        <img src="{{blog.image.url}}" width="300px" height="200px" alt="" />

        <p>{{blog.publish_date}}</p>
        <p>{{blog.type}}</p>
        <h4><a href="#">{{blog.name}}</a></h4>
        <p>{{blog.describtion}}</p>
     
        <a href="#">Read More</a>
      </div>
    
    {%endfor%}
  </div>
</section>

{% endblock %}