login/urls.py
from django.urls import path
from login import views

app_name = 'login'

urlpatterns = [
    path('signupcompany/', views.signupcompany, name='signupcompany'),
    path('', views.index, name='index'),
    path('logincompany/', views.logincompany, name='logincompany'),
    path('signupcustomer/', views.signupcustomer, name='signupcustomer'),
    path('logincustomer/', views.logincustomer, name='logincustomer'),
    path('afterlogincompany/', views.afterlogincompany, name='afterlogincompany'),
    path('afterlogincustomer/', views.afterlogincustomer,
         name='afterlogincustomer'),
    path('logout/', views.logout_user, name='logout'),
    path('', views.index, name='index'),




]

tastyfood/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('company.urls')),
    path('', include('customer.urls')),
    path('', include('login.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" />
    <!-- Latest compiled and minified CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="static/css/style.css" />
    <title>{% block title_block %} Tastyfood {% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-white shadow py-3 sticky-top">
      <div class="container">
        <a class="navbar-brand" href="/">
          <b>
            <h3>Tasty <span style="color: #da2626">Food</span></h3></b
          >
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mx-auto">
            <li class="nav-item">
              <a class="nav-link" href=""></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#menu">Menu</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#features">Features</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#team">Team</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Reservation</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#blog">Blog</a>
            </li>
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                sign up
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a
                    class="dropdown-item"
                    href="{% url 'login:signupcompany' %}"
                    >sign up as company</a
                  >
                </li>
                <li>
                  <a
                    class="dropdown-item"
                    href="{% url 'login:signupcustomer' %}"
                    >sign up as customer</a
                  >
                </li>
              </ul>
            </li>

            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Log in
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a class="dropdown-item" href="{% url 'login:logincompany' %}"
                    >Log in as company</a
                  >
                </li>
                <li>
                  <a
                    class="dropdown-item"
                    href="{% url 'login:logincustomer' %}"
                    >Log in as customer</a
                  >
                </li>
              </ul>
            </li>
          </ul>
          <a href="{% url 'login:logincustomer' %}" class="btn btn-brand">
            order online
          </a>
        </div>
      </div>
    </nav>

    {% comment %}
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href=""
            ><img src="/media/logo.png" width="50px"
          /></a>
        </li>

        <div class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbardrop"
            data-toggle="dropdown"
          >
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="">Write Blog</a>
            <a class="dropdown-item" href="">My Blogs</a>
            <a class="dropdown-item" href="">Your Profile</a>
            <hr />
            <a class="dropdown-item" href="{% url 'login:logout' %}">Logout</a>
          </div>
        </div>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'login:signupcompany' %}"
            >SignUp company</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login:logincompany' %}"
            >Login company</a
          >
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'login:signupcustomer' %}"
            >Sign Up</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login:logincustomer' %}">Login</a>
        </li>
      </ul>
    </nav>
    {% endcomment %} {% block body %} {% endblock %}

    <!-- footer -->

    {% comment %}
    <footer class="bg-cover">
      <div class="footer-top">
        <div class="container">
          <div class="row gy-5">
            <div class="col-lg-4">
              <a class="navbar-brand" href="#">
                <b>
                  <h3>
                    <span style="color: white"> Tasty</span>
                    <span style="color: #f58d17">Treat</span>
                  </h3></b
                >
              </a>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Reprehenderit architecto unde magnam.
              </p>
              <div class="social-links">
                <a href="#"><i class="ri-facebook-circle-fill"></i></a>
                <a href="#"><i class="ri-instagram-fill"></i></a>
                <a href="#"><i class="ri-youtube-fill"></i></a>
                <a href="#"><i class="ri-google-play-fill"></i></a>
              </div>
            </div>
            <div class="col-lg-3 ms-auto">
              <h6 class="text-white mb-4">CONTACT</h6>
              <p class="mb-1">P:(03) 9283 4726</p>
              <p class="mb-1">E:enquiries@mill.co</p>
              <p class="mb-0">
                A: 14 Paramore Street Mornington Peninsula Victoria 3552
              </p>
            </div>
            <div class="col-lg-3">
              <h6 class="text-white mb-4">OPENING HOURS</h6>
              <p class="mb-1">PMonday-Friday : 08:00 - 22:00</p>
              <p>aturday-Sunday : 08:00 - 22:00</p>
            </div>
          </div>
        </div>
      </div>
      <div class="footer-bottom">
        <div class="container">
          <div class="row gy-3 justify-content-between">
            <div class="col-auto">
              <p class="mb-0">Copyrights all rights reserved</p>
            </div>
            <div class="col-auto">
              <p class="mb-0">
                Designed By
                <a href="https://www.youtube.com/c/SA7MAN">Salman</a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </footer>
    {% endcomment %}

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
      crossorigin="anonymous"
    ></script>
  </body>
</html>